version: "3.9"
services:
        build_data:
                #build: .
                image: pkg:latest
                container_name: build_data
                stdin_open: true
                tty: true
                environment:
                  - datafile=pathtodatafile
                  - samplefile=pathtosample
                command: ["python3","-m","pkg_baseline.py", "--type", "sample"]

        build_pkg:
                image: pkg:latest
                container_name: build_pkg
                stdin_open: true
                tty: true
                volumes:
                  - ./triple_extraction:/code/triple_extraction
                  - ./data:/code/data
                  - ./outputs:/code/outputs
                  - ./coreference_resolution:/code/coreference_resolution
                  - ${PWD}/pkg_baseline.py:/code/pkg_baseline.py
                depends_on:
                  - run_coref
                links:
                  - "run_coref:localhost"
                command: ["python3","pkg_baseline.py", "--type", "sample"] #triple_extraction/SPN4RE/predict.py
                environment:
                  - DATA=pathtofile
                  - bert=/code/bert-base-cased/
                  - datafile=/code/data/ConvAI2/test_both_original_final.txt
                  - samplefile=/code/outputs/sample.json
                  - traindata=/code/triple_extraction/SPN4RE/data/WebNLG/clean_WebNLG/train_new_new_v2.json
                  - validdata=/code/triple_extraction/SPN4RE/data/WebNLG/clean_WebNLG/valid_new_new_v2.json
                  - testdata=/code/triple_extraction/SPN4RE/data/WebNLG/clean_WebNLG/test_new_new_v2.json
                  - generated_data=/code/outputs/generated_data/
                  - modelpath=/code/nSetPred4RE_WebNLG_epoch_3_f1_0.3928.model
                  - logs=/code/outputs/logs
        run_coref:
                image: coref:latest
                build:
                  context: .
                  dockerfile: ./coreference_resolution/Dockerfile
                container_name: run_coref
                stdin_open: true
                tty: true
                ports:
                  - "9001:9001"
                command: java -mx4g -cp "stanford-corenlp-4.4.0/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9001 -timeout 15000

        train_model:
                image: test:test
                #depends_on:
                #  - build_data
                container_name: model_train
                stdin_open: true #docker run -i
                tty: true # docker run -t
                command: ["python3","/code/triple_extraction/SPN4RE/main.py"]
                volumes:
                        - type: bind
                          source: ./outputs 
                          target: /code/outputs
                        - type: bind
                          source: ./outputs
                          target: /code/data

                environment:
                  - traindata=/data/train.json
                  - validdata=/data/valid.json
                  - testdata=/data/test.json
                  - generated_data=/outputs/generated_data/
                  - bert=/code/bert-base-cased/
                  - modelpath=/outputs/model/
                  - logs=/outputs/logs



        architecture01:
                image: test:test
                container_name: SPNarchitecture
                stdin_open: true
                tty: true
                command: ["python3","/code/triple_extraction/SPN4RE/predict.py"]
                volumes:
                  - type: bind
                    source: ./triple_extraction
                    target: /code/triple_extraction
                environment:
                  - trainedmodel=/code/nSetPred4RE_WebNLG_epoch_3_f1_0.3928.model
                  - trainedargs=/code/args.pickle
                  - traindata=/data/train.json
                  - validdata=/data/valid.json
                  - testdata=/data/test.json
                  - generated_data=/outputs/generated_data/
                  - bert=/code/bert-base-cased/